### ISSUE TITLE
Spreadsheet component

### ISSUE THREAD

**Issue by jivanova** [test-web-components/web-components#25]
```[tasklist]
### Tasks
- [ ] Create design and UX prototypes 
- [ ] Implement rendering and styling
- [ ] Engineering implementation
- [ ] Add in ThemeBuilder
```
